num1=int(input("enter num1 "))
num2=int(input("enter num2"))
print("Addition ",num1+num2)
print("Substraction ",num1-num2)
print("Multiplication ",num1*num2)
print("division ",num1/num2)
print("Modulus ",num1%num2)
print("Exponent ",num1**num2)
print("floor division ",num1//num2)