print("Please enter your details for your self introduction")
name=input("Name: ")
place=input("Current Location: ")
age=input("Age: ")
qualification=input("Qualification: ")
print("SELF INTRODUCTION")
print('Hi my name is',name,'and I am currently living in',place,'. I am a',age,'year old',qualification,'graduated person')
